### PR TITLE
Add de_vertigo and update radar images

### PR DESCRIPTION
**Pull request by CorySanin**

### CODE REVIEW

**Comment by Musty260** [comment]
Did this commit add vertigo to the stats screen, showing the wins, losses and draws in those pie charts and bar charts because if it did it doesn't come up for me; Cobblestone's still there but I don't have any demos saved for that.

**Comment by CorySanin** [comment]
Hmm... I wasn't aware there was such a screen. I don't see why vertigo wouldn't appear, but I'll investigate. Thanks for letting me know!

**Comment by CorySanin** [comment]
@Musty260 Ah, I see. It only shows a subset of the maps the manager supports. Since it looks like it's meant to show the stats for active duty maps, I've replaced Cobble with Vertigo. Try it now! 😀

**Comment by CorySanin** [comment]
@akiver can I get some feedback? This PR was opened in March 😏

**Comment by akiver** [comment]
> @akiver can I get some feedback? This PR was opened in March 😏

Hi, sorry for the delay, I don't have a full Windows environment since months, this is why the PRs are inactive (I'm using a virtual env which is not optimal but it should changes soon).  

About the PR, could you please remove the code related to the switch between cbble and vertigo?  
The maps stats screen should not be limited to the active duty maps.  
This is poorly handled by the actual implementation but if you want to add a map on the stats screen, it should be done the same way as for others maps.

Thanks

**Comment by CorySanin** [comment]
Understood! Will add cobble back. Thanks 👍

**Comment by Musty260** [comment]
Wait if I personally wanted to have vertigo on the stats screen, could there be something I could do to keep it? I wouldn't mind having to edit some files or something if needed

**Comment by CorySanin** [comment]
@Musty260 I intend to have both cobble and vertigo. I meant I'll add cobble back in addition to vertigo. Relax! 😂

**Comment by CorySanin** [comment]
There! Now both Cobble and Vertigo are displayed in the stats screen.

**Comment by akiver** [comment]
Thank you!

**Pull request merged**
